import type { Node } from "../engine/model";
import { collectBindings, collectProgressNodes, pathToCamel, resolveDefault } from "./helpers";

export function generateBubbleTea(doc: Node, _cols: number, mockData: unknown): string {
  const bindings  = collectBindings(doc);
  const progNodes = collectProgressNodes(doc);

  const modelFields = bindings.map((path) => {
    const def  = resolveDefault(path, mockData);
    const name = pathToCamel(path);
    if (typeof def === "number") return "    " + name + " int    // {{" + path + "}}";
    return "    " + name + " string // {{" + path + "}}";
  });

  const initFields = bindings.map((path) => {
    const def  = resolveDefault(path, mockData);
    const name = pathToCamel(path);
    if (typeof def === "number") return "        " + name + ": " + Math.round(+(def as number)) + ",";
    if (typeof def === "string") return '        ' + name + ': "' + def + '",';
    return '        ' + name + ': "",';
  });

  const viewLines = progNodes.map((n) => {
    const fieldName = pathToCamel(n.valueBind);
    const label     = (n.label || "").trim() || "Progress";
    return '    view += progressBar(m.' + fieldName + ', 30, "' + label.padEnd(8) + '") + "\\n"';
  });

  return [
    "// Generated by Edda — terminal interface designer",
    "// Install: go get github.com/charmbracelet/bubbletea",
    "//          go get github.com/charmbracelet/lipgloss",
    "",
    "package main",
    "",
    "import (",
    '    "fmt"',
    '    "strings"',
    '    tea "github.com/charmbracelet/bubbletea"',
    '    "github.com/charmbracelet/lipgloss"',
    ")",
    "",
    "var (",
    '    accentStyle = lipgloss.NewStyle().Foreground(lipgloss.Color("#5fd7a0"))',
    '    dimStyle    = lipgloss.NewStyle().Foreground(lipgloss.Color("#8b909c"))',
    '    borderStyle = lipgloss.NewStyle().Border(lipgloss.NormalBorder()).BorderForeground(lipgloss.Color("#2b313b")).Padding(0, 1)',
    ")",
    "",
    "// Model holds application state — replace with your real data source",
    "type Model struct {",
    ...(modelFields.length ? modelFields : ["    // (no data bindings found)"]),
    "}",
    "",
    "func initialModel() Model {",
    "    return Model{",
    ...(initFields.length ? initFields : ["        // defaults"]),
    "    }",
    "}",
    "",
    "func (m Model) Init() tea.Cmd { return nil }",
    "",
    "func (m Model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {",
    "    switch msg := msg.(type) {",
    "    case tea.KeyMsg:",
    '        if msg.String() == "q" || msg.String() == "ctrl+c" {',
    "            return m, tea.Quit",
    "        }",
    "    }",
    "    return m, nil",
    "}",
    "",
    "func (m Model) View() string {",
    "    var view string",
    ...(viewLines.length ? viewLines : ['    view += "TODO: render layout\\n"']),
    "    return borderStyle.Render(view)",
    "}",
    "",
    "func progressBar(value, width int, label string) string {",
    "    filled := width * value / 100",
    "    if filled < 0 { filled = 0 }",
    "    if filled > width { filled = width }",
    "    bar := accentStyle.Render(strings.Repeat(\"█\", filled)) +",
    "        dimStyle.Render(strings.Repeat(\"░\", width-filled))",
    '    return fmt.Sprintf("%s %s %3d%%", label, bar, value)',
    "}",
    "",
    "func main() {",
    "    p := tea.NewProgram(initialModel(), tea.WithAltScreen())",
    '    if _, err := p.Run(); err != nil { fmt.Printf("Error: %v\\n", err) }',
    "}",
  ].join("\n");
}
