import type { Node } from "../engine/model";
import { collectBindings, collectProgressNodes, pathToCamel, resolveDefault, getTitle } from "./helpers";

export function generateInk(doc: Node, _cols: number, mockData: unknown): string {
  const bindings  = collectBindings(doc);
  const progNodes = collectProgressNodes(doc);
  const title     = getTitle(doc);

  const propTypes = bindings.map((path) => {
    const def  = resolveDefault(path, mockData);
    const name = pathToCamel(path);
    if (typeof def === "number") return "  " + name + " = " + def + ",  // {{" + path + "}}";
    if (typeof def === "string") return '  ' + name + ' = "' + def + '",  // {{' + path + '}}';
    return "  " + name + ' = "",';
  });

  const progressComps = progNodes.map((n) => {
    const name  = pathToCamel(n.valueBind);
    const label = (n.label || "").trim() || "Progress";
    return [
      "      <Box key=" + JSON.stringify(n.valueBind) + ">",
      '        <Text dimColor>' + label.padEnd(8) + "</Text>",
      "        <ProgressBar value={" + name + "} />",
      "      </Box>",
    ].join("\n");
  });

  return [
    "// Generated by Edda — terminal interface designer",
    "// Install: npm install ink react",
    "// Run:     node --input-type=module < app.jsx",
    "",
    'import React from "react";',
    'import { render, Text, Box, Newline } from "ink";',
    "",
    "// Simple progress bar component",
    "const ProgressBar = ({ value = 0, width = 20 }) => {",
    "  const filled = Math.round(width * value / 100);",
    "  const empty  = width - filled;",
    '  return <Text><Text color="green">{"█".repeat(filled)}</Text><Text dimColor>{"░".repeat(empty)}</Text><Text color="green"> {String(value).padStart(3)}%</Text></Text>;',
    "};",
    "",
    "// Main app component",
    "const App = ({",
    ...(propTypes.length ? propTypes : ["  // (no data bindings — add props here)"]),
    "}) => (",
    '  <Box flexDirection="column" borderStyle="single" paddingX={1}>',
    '    <Text bold color="green">' + title.replace(/<|>/g, "") + "</Text>",
    '    <Text dimColor>{"─".repeat(40)}</Text>',
    ...(progressComps.length ? [
      '    <Box flexDirection="column">',
      ...progressComps,
      "    </Box>",
    ] : [
      '    <Text>TODO: add your components here</Text>',
    ]),
    "  </Box>",
    ");",
    "",
    "// Entry point — replace static props with your real data",
    "render(",
    "  <App",
    ...bindings.map((path) => {
      const def  = resolveDefault(path, mockData);
      const name = pathToCamel(path);
      if (typeof def === "number") return "    " + name + "={" + Math.round(+(def as number)) + "}";
      if (typeof def === "string") return '    ' + name + '="' + def + '"';
      return "    " + name + '=""';
    }),
    "  />",
    ");",
  ].join("\n");
}
