import type { Node } from "../engine/model";
import { collectBindings, collectProgressNodes, pathToRust, resolveDefault } from "./helpers";

export function generateRatatui(doc: Node, _cols: number, mockData: unknown): string {
  const bindings  = collectBindings(doc);
  const progNodes = collectProgressNodes(doc);

  const stateFields = bindings.map((path) => {
    const def  = resolveDefault(path, mockData);
    const name = pathToRust(path);
    if (typeof def === "number") return "    pub " + name + ": u16,  // {{" + path + "}}";
    if (typeof def === "string") return "    pub " + name + ': String,  // {{' + path + '}}';
    return "    pub " + name + ": String,";
  });

  const defaultFields = bindings.map((path) => {
    const def  = resolveDefault(path, mockData);
    const name = pathToRust(path);
    if (typeof def === "number") return "            " + name + ": " + Math.round(+(def as number)) + ",";
    if (typeof def === "string") return '            ' + name + ': "' + def + '".to_string(),';
    return "            " + name + ': "".to_string(),';
  });

  const gaugeLines = progNodes.map((n, i) => {
    const fieldName = pathToRust(n.valueBind);
    const label     = (n.label || "").trim() || "Progress";
    return [
      "    let gauge_" + i + " = Gauge::default()",
      '        .block(Block::default().title("' + label + '").borders(Borders::ALL))',
      "        .percent(state." + fieldName + ")",
      "        .gauge_style(Style::default().fg(Color::Green));",
      "    f.render_widget(gauge_" + i + ", layout[" + i + "]);",
    ].join("\n");
  });

  const constraintCount = Math.max(progNodes.length, 2);
  const constraints = Array.from({ length: constraintCount }, (_, i) =>
    i < progNodes.length ? "            Constraint::Length(3)," : "            Constraint::Min(0),"
  );

  return [
    "// Generated by Edda — terminal interface designer",
    "// Add to Cargo.toml:",
    "//   ratatui = \"0.26\"",
    "//   crossterm = \"0.27\"",
    "",
    "use ratatui::{",
    "    layout::{Constraint, Direction, Layout},",
    "    style::{Color, Style, Modifier},",
    "    widgets::{Block, Borders, Gauge, Paragraph, Table, Row, Cell},",
    "    text::{Line, Span},",
    "    Frame,",
    "};",
    "",
    "// --- application state (populate from your data source) ---",
    "#[derive(Debug, Default)]",
    "pub struct AppState {",
    ...(stateFields.length ? stateFields : ["    // (no data bindings found)"]),
    "}",
    "",
    "impl AppState {",
    "    pub fn new() -> Self {",
    "        AppState {",
    ...(defaultFields.length ? defaultFields : ["            ..Default::default()"]),
    "        }",
    "    }",
    "}",
    "",
    "// --- render function (call from your event loop) ---",
    "pub fn render(f: &mut Frame, state: &AppState) {",
    "    let size = f.size();",
    "    let layout = Layout::default()",
    "        .direction(Direction::Vertical)",
    "        .margin(1)",
    "        .constraints([",
    ...(constraints.length ? constraints : ["            Constraint::Min(0),"]),
    "        ])",
    "        .split(size);",
    "",
    ...(gaugeLines.length ? gaugeLines : [
      "    // TODO: render your components here",
      "    let p = Paragraph::new(\"Edda layout\");",
      "    f.render_widget(p, layout[0]);",
    ]),
    "}",
    "",
    "// --- main entry point ---",
    "// fn main() -> Result<(), Box<dyn std::error::Error>> {",
    "//     use crossterm::event::{self, Event, KeyCode};",
    "//     crossterm::terminal::enable_raw_mode()?;",
    "//     let mut terminal = ratatui::init();",
    "//     let state = AppState::new();",
    "//     loop {",
    "//         terminal.draw(|f| render(f, &state))?;",
    "//         if let Event::Key(k) = event::read()? {",
    "//             if k.code == KeyCode::Char('q') { break; }",
    "//         }",
    "//     }",
    "//     ratatui::restore();",
    "//     Ok(())",
    "// }",
  ].join("\n");
}
