import type { Node } from "../engine/model";
import { renderAsciiText } from "../engine/borders";
import { collectBindings, collectProgressNodes, pathToVar, resolveDefault, getTitle } from "./helpers";

function buildTextualCompose(node: Node, indent: string): string {
  const lines: string[] = [];
  function walk(n: Node, ind: string) {
    if (!n) return;
    switch (n.type) {
      case "box":
        lines.push(ind + 'with Container(classes="panel"):');
        if ("children" in n && n.children) (n.children as Node[]).forEach((c) => walk(c, ind + "    "));
        break;
      case "split":
        lines.push(ind + "with Horizontal():");
        if ("children" in n && n.children) (n.children as Node[]).forEach((c) => walk(c, ind + "    "));
        break;
      case "column":
        lines.push(ind + "with Vertical():");
        if ("children" in n && n.children) (n.children as Node[]).forEach((c) => walk(c, ind + "    "));
        break;
      case "progress": {
        const label = n.label ? n.label.trim() : "Progress";
        lines.push(ind + 'yield Label("' + label + '")');
        lines.push(ind + "yield ProgressBar(total=100)  # bind: " + (n.valueBind || "static " + (n.value || 0) + "%"));
        break;
      }
      case "text":
        if (n.content) {
          lines.push(ind + 'yield Label(f"' + n.content.replace(/"/g, "'") + '")');
        }
        break;
      case "status":
        lines.push(ind + 'yield Static("● " + str(self.' + (n.stateBind ? pathToVar(n.stateBind) : '"' + (n.state || "ok") + '"') + '), classes="accent")');
        break;
      case "table": {
        lines.push(ind + "table = DataTable()");
        (n.columns || []).forEach((c) => lines.push(ind + 'table.add_column("' + (typeof c === "object" ? c.label : c) + '")'));
        lines.push(ind + "# TODO: populate table rows with real data");
        lines.push(ind + "yield table");
        break;
      }
      case "divider":
        lines.push(ind + 'yield Static("─" * ' + 40 + ')');
        break;
      case "ascii": {
        const banner = renderAsciiText(n.content || "", { fillChar: n.fillChar || "█" });
        const esc = banner.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
        lines.push(ind + 'yield Static("\\n' + esc + '\\n", classes="accent")  # ASCII banner: ' + (n.content || ""));
        break;
      }
      case "spacer":
        lines.push(ind + 'yield Static("")');
        break;
      default:
        if ("children" in n && n.children) (n.children as Node[]).forEach((c) => walk(c, ind));
        break;
    }
  }
  walk(node, indent);
  return lines.join("\n");
}

export function generateTextual(doc: Node, cols: number, mockData: unknown): string {
  const bindings  = collectBindings(doc);
  const title     = getTitle(doc);
  const progNodes = collectProgressNodes(doc);

  const stateLines = bindings.map((path) => {
    const def  = resolveDefault(path, mockData);
    const name = pathToVar(path);
    if (typeof def === "number") return "    " + name + ": reactive = " + def + "  # {{" + path + "}}";
    if (typeof def === "string") return '    ' + name + ': reactive = "' + def + '"  # {{' + path + '}}';
    return "    " + name + ": reactive = None  # {{" + path + "}}";
  });

  const mountLines = progNodes.map((n, i) => {
    const def = resolveDefault(n.valueBind, mockData);
    const pct = def != null ? Math.round(+(def as number)) : 0;
    return '        self.query_one("#progress-' + i + '", ProgressBar).progress = ' + pct + "  # " + n.valueBind;
  });

  const composeBody = buildTextualCompose(doc, "        ");

  return [
    "# Generated by Edda — terminal interface designer",
    "# Install: pip install textual",
    "# Run:     python app.py",
    "",
    "from textual.app import App, ComposeResult",
    "from textual.widgets import Header, Footer, Static, Label, ProgressBar, DataTable",
    "from textual.containers import Vertical, Horizontal, Container",
    "from textual.reactive import reactive",
    "",
    "",
    'class EddaApp(App):',
    '    """' + title.replace(/"/g, "'") + ' — generated by Edda"""',
    "",
    "    CSS = \"\"\"",
    "    Screen { background: #0d1117; color: #e6e8ec; }",
    "    .panel { border: solid #2b313b; padding: 0 1; }",
    "    .accent { color: #5fd7a0; }",
    "    \"\"\"",
    "",
    "    # --- reactive state (replace with your data source) ---",
    ...(stateLines.length ? stateLines : ["    # (no data bindings found)"]),
    "",
    "    def compose(self) -> ComposeResult:",
    '        yield Header(show_clock=True)',
    composeBody || '        yield Label("Layout")',
    '        yield Footer()',
    "",
    "    def on_mount(self) -> None:",
    "        # TODO: connect your real data source here",
    ...(mountLines.length ? mountLines : ["        pass"]),
    "",
    "",
    'if __name__ == "__main__":',
    "    EddaApp().run()",
  ].join("\n");
}
